{% set name = "howardhinnant_date" %}
{% set version = "3.0.0" %}
{% set sha256 = "87bba2eaf0ebc7ec539e5e62fc317cb80671a337c1fb1b84cb9e4d42c6dbebe3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/HowardHinnant/date/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - libcurl
  run:
    - libcurl

test:
  commands:
    - test -d ${PREFIX}/include/date  # [unix]
    - test -f ${PREFIX}/include/date/date.h  # [unix]
    - test -f ${PREFIX}/lib/libdate-tz${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/cmake/date/dateConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\date\date.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\date-tz.dll (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\dateConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/HowardHinnant/date
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A C++ date and time library
  description: A date and time library based on the C++11/14/17 <chrono> header
  doc_url: http://howardhinnant.github.io/date/date.html
  dev_url: http://github.com/HowardHinnant/date

extra:
  recipe-maintainers:
    - pidefrem
