travis:
  secure:
    BINSTAR_TOKEN: W9ighuZMk390YOlnPfOJZCaqxMX2KJBGs83OG0oJVtwcNu309S0h7B3VPRIkCTXViJVAPacPXTk2GnY9lHzVnk1cmLhxiPeVZtNrnI8F9ZzSo6X0m1J/ObMsm1VCMcRy2fOjUT+2RFmRHaFhwrDOuXbGBxSwIJPr6rRMHhWeewFzE7ULbBCuxxAjrNvJJCibIVDjfJ50hPCFOiy7iVWTLG34A2ePP5gsH0PXbF60gYXaekOyQNREab+n9uuTrZcFP7iR1yXT+0B+x/ffDmT2sG0SmvOVYOH4IzSag8IJ0xV1zXlpLa9BqqSY9h2CWCr5d3YPB3owIbPDg0298k2wFUPR0gwHoYksSWKbHHZhnwGs1A1PpWN/UvkdreGL7MmWNa3R0yUTNmogtUkBCucfIQSOOUaRu9fAu2i6VHbVwcG0iTSUgof4aACg/zBYDCu19zh10n3S1IXOszzbOPoBTqfFqb/Ltr7JawHUHkxxtgyAaLmvlY09s6TAHZY4YE+LelY5KUBoS/A4yCVqR2WBHz1X0l++pPDiU6NKuuhJ3JY40b3wpIRwm2MI9yIwUT9Zt5iVbesKjcXLY3cEjIOfbvgjvNGu3dBXnd3psLCGoIW6i3Ykv/98RlmXt0t0rUxe0aTDLKa6c1AdF6A7ahYFyQZDwkgXnICrtZQO5zK/mrw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
